### ISSUE TITLE
IncorrectJaxRsPluginsException: ERROR!  No jax-rs application plugins found 

### ISSUE THREAD

**Issue by mario786** [aol/micro-server#162]
I am using Microboot- hoping to leverage SpringBoot and use the Grizzly server too. I am getting the following error:

Exception in thread "My-Web-Service" com.aol.micro.server.module.IncorrectJaxRsPluginsException: ERROR!  No jax-rs application plugins found 
	at com.aol.micro.server.servers.JaxRsServletConfigurer.addServlet(JaxRsServletConfigurer.java:25)
	at com.aol.micro.server.servers.grizzly.GrizzlyApplication.run(GrizzlyApplication.java:69)
	at com.aol.micro.server.servers.ServerRunner.lambda$start$54(ServerRunner.java:69)
	at com.aol.micro.server.servers.ServerRunner$$Lambda$85/1192603187.run(Unknown Source)

I have this application class sitting in the base package:
@Microboot
public class App {

    public static void main(String[] args) {

        new MicroserverApp(() -> "My-Web-Service").start();
    }
}

I have my web service define like this in a sub package:
@Rest
@Path("/my-web-service")
public class MyWebService {
...
}

When I run the App I can see promising logs like these:
2016-03-02 18:55:04,276 INFO [main] c.g.o.r.e.t.a.App [StartupInfoLogger.java:57] Started App in 11.605 seconds (JVM running for 13.857)
2016-03-02 18:55:04,298 DEBUG [main] o.s.b.f.s.DefaultListableBeanFactory [AbstractBeanFactory.java:251] Returning cached instance of singleton bean 'myWebService'

However, I also get the above error and my web service does not respond http requests.

Any ideas how to solve this problem?

Thanks

**Comment by johnmcclean-aol** [comment]
Hi Mario,

Add micro-jersey to the classpath to add a jax-rs plugin to your app. 

https://github.com/aol/micro-server/tree/master/micro-jersey

**Comment by johnmcclean-aol** [comment]
Further to that if you have micro-jersey on the classpath but are still seeing this error, the most likely cause is that the plugin files in micro-jersey are being overwriten during the generation of a 'fat' jar. With gradle shadow jar you can write

```groovy
    shadowJar {
      mergeServiceFiles()  
    }
```

**Comment by mario786** [comment]
Brilliant! Adding micro-jersey to the classpath solved it.
Thanks very much for such a quick response :)

**Comment by mario786** [comment]
Is there a way to configure the http port on which Grizzly listens to in the above setup?

**Comment by earlzero** [comment]
You can set `My-Web-Service.port` property to port value

**Comment by johnmcclean-aol** [comment]
@mario786  as @earlzero  says you can use a property (either in a properties file, or via Microserver annotation or as a system property). E.g. your application will look for a file application.properties on the classpath or in the user directory and if that has a property 

My-Web-Service.port=8090

Then the port will be set to 8090.

https://github.com/aol/micro-server/wiki/Defining-Properties

https://github.com/aol/micro-server/wiki/Configuring-the-port-or-hostname

**Comment by mario786** [comment]
That's lovely! Thanks very much for your help guys :)
Note to self: Put some effort in reading the Wiki before asking :P
