### ISSUE TITLE
Service Registry Registration fails if sigar-lib can not be loaded.

### ISSUE THREAD

**Issue by tonyfinn** [aol/micro-server#288]
If sigar-lib is missing or otherwise unable to load, MachineStatsChecker.getCpuStats throws an UnsatisfiedLinkError, which is not caught and causes the service registry registration to fail.

java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
        at org.hyperic.sigar.Cpu.gather(Native Method) ~[ingester.jar:1.0.0-SNAPSHOT]
        at org.hyperic.sigar.Cpu.fetch(Cpu.java:30) ~[ingester.jar:1.0.0-SNAPSHOT]
        at org.hyperic.sigar.Sigar.getCpu(Sigar.java:320) ~[ingester.jar:1.0.0-SNAPSHOT]
        at org.hyperic.sigar.Sigar.getCpuPerc(Sigar.java:341) ~[ingester.jar:1.0.0-SNAPSHOT]
        at com.aol.micro.server.machine.stats.sigar.MachineStatsChecker.getCpuStats(MachineStatsChecker.java:66) ~[ingester.jar:1.0.0-SNAPSHOT]
        at com.aol.micro.server.machine.stats.sigar.MachineStatsChecker.cpuStats(MachineStatsChecker.java:38) ~[ingester.jar:1.0.0-SNAPSHOT]
        at com.aol.micro.server.machine.stats.sigar.SigarStats.get(SigarStats.java:30) ~[ingester.jar:1.0.0-SNAPSHOT]
        at com.aol.micro.server.machine.stats.sigar.SigarStats.get(SigarStats.java:12) ~[ingester.jar:1.0.0-SNAPSHOT]
        at com.aol.micro.server.application.registry.RegistryStatsChecker$$Lambda$203/1944160964.apply(Unknown Source) ~[na:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_31]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.

**Comment by johnmcclean-aol** [comment]
Merged in https://github.com/aol/micro-server/pull/290
