### ISSUE TITLE
WrongMethodTypeException: cannot convert MethodHandle(Object)Optional to (Object,Object)Object

### ISSUE THREAD

**Issue by colmg** [aol/micro-server#52]
Hi,

I am in the process of upgrading to version 0.62.

at startup, I'm calling JacksonUtil.getMapper() which causes this failure in cyclops.
stack trace below.

When I comment out the getMapper, I get a similar failure when getDefaultJaxRsPackage() is called.

Have you seen this before, or any ideas ?

Exception in thread "main" java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(Object)Optional to (Object,Object)Object
	at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:770)
	at java.lang.invoke.Invokers.checkGenericType(Invokers.java:366)
	at com.aol.cyclops.lambda.api.InvokeDynamic.executeMethod(InvokeDynamic.java:106)
	at com.aol.cyclops.lambda.api.InvokeDynamic.execute(InvokeDynamic.java:60)
	at com.aol.cyclops.lambda.api.InvokeDynamic.lambda$execute$119(InvokeDynamic.java:44)
	at com.aol.cyclops.lambda.api.InvokeDynamic$$Lambda$39/149047107.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.aol.cyclops.lambda.api.InvokeDynamic.execute(InvokeDynamic.java:44)
	at com.aol.cyclops.comprehensions.comprehenders.InvokeDynamicComprehender.of(InvokeDynamicComprehender.java:158)
	at com.aol.cyclops.lambda.api.Comprehender.resolveForCrossTypeFlatMap(Comprehender.java:154)
	at com.aol.cyclops.lambda.api.Comprehender.unwrapOtherMonadTypes(Comprehender.java:140)
	at com.aol.cyclops.lambda.api.Comprehender.lambda$executeflatMap$2(Comprehender.java:92)
	at com.aol.cyclops.lambda.api.Comprehender$$Lambda$31/926370398.apply(Unknown Source)
	at com.aol.cyclops.comprehensions.comprehenders.InvokeDynamicComprehender.lambda$flatMap$27(InvokeDynamicComprehender.java:133)
	at com.aol.cyclops.comprehensions.comprehenders.InvokeDynamicComprehender$$Lambda$36/422392391.apply(Unknown Source)
	at com.aol.cyclops.comprehensions.comprehenders.FunctionExecutionInvocationHandler.invoke(FunctionExecutionInvocationHandler.java:23)
	at com.sun.proxy.$Proxy3.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.aol.cyclops.lambda.monads.SequenceM.forEach(SequenceM.java:1415)
	at com.aol.micro.server.rest.jackson.JacksonUtil.getMapper(JacksonUtil.java:42)
	at com.aol.advertising.psm.campaign.bootstrap.CampaignStartup.main(CampaignStartup.java:43)

**Comment by johnmcclean-aol** [comment]
Hey Colm,

Yes - Microserver makes use of the Java Service Loader mechanism to load in
plugins. If something (e.g. fat jar plugin) overwrites the
META-INF/services/com.aol.micro.server.Plugin  definition file from
multiple plugins, you get an error similar to that one. (Same issue can
occur with Cyclops). So the solution is to make sure that Service
definitons are merged rather than overwritten.

With the shadowJar plugin for Gradle you can do this by adding this to your
build file :-

shadowJar {
  mergeServiceFiles()
}

**Comment by colmg** [comment]
excellent, that solved my problem.

**Comment by johnmcclean-aol** [comment]
Cool, I don't know why over writing them is the default behaviour in the
plugin.
